declare type errorPlacementValue = 'top' | 'bottom';
export declare function errorPlacementDefault(): errorPlacementValue;
export declare function setErrorPlacementDefault(value: errorPlacementValue): void;
export declare function alertSendsAnalytics(): boolean;
export declare function setAlertSendsAnalytics(value: boolean): void;
export declare function dialogSendsAnalytics(): boolean;
export declare function setDialogSendsAnalytics(value: boolean): void;
export declare function helpDrawerSendsAnalytics(): boolean;
export declare function setHelpDrawerSendsAnalytics(value: boolean): void;
export {};
